name: Node.js CI Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        tests:
          - Libs/Array.*
          - Libs/Integrator.*
          - Libs/Polynomials.*
          - Libs/Power.*
          - APower/APower.*
          - XPower/XPower.*
          - XPowerNft/XPowerNft.*
          - XPowerPpt/XPowerPpt.*
          - NftTreasury/NftTreasury.*
          - MoeTreasury/MoeTreasury.*

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: NPM install and build
        run: |
          npm ci
          npm run build --if-present

      - name: NPM test ${{ matrix.tests }}
        run: npm run -- test ./test/${{ matrix.tests }}
